import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

import java.awt.BorderLayout;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import org.jfree.data.category.DefaultCategoryDataset;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author kagan
 */

public class StokPaneli extends javax.swing.JFrame {
    DatabaseProcesses processes = new DatabaseProcesses();
    DefaultTableModel model;
    
    /**
     * Creates new form StokPanel
     */
    public StokPaneli() {
        initComponents();
                piechartpanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        model = (DefaultTableModel) urunTable.getModel();
        showProducts();
        createPieChart();
        synchronized (KullaniciThread.class) {
                    AppContext.isAdminProcessing = true;
                    AppContext.pauseAllUserThreads();

            
        }
        // Panel açıldığında tüm thread'leri durdur
        //System.out.println("Admin basladı");
    }
    
// Panel kapatıldığında thread'leri yeniden başlat
    @Override
    public void dispose() {
    super.dispose();
    AppContext.isAdminProcessing = false;
    AppContext.resumeAllUserThreads();
    synchronized (KullaniciThread.class) {
        KullaniciThread.class.notifyAll(); // Tüm bekleyen thread'leri uyandır
        //System.out.println("Tüm thread'ler yeniden başlatıldı.");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        urunTable = new javax.swing.JTable();
        chartpanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        urunadiTF = new javax.swing.JTextField();
        urunfiyatiTF = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        urunadetSpinner = new javax.swing.JSpinner();
        urunekleButton = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        urunfiyatiguncelleTF = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        urunadiguncelleTF = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        urunadetguncelleSpinner = new javax.swing.JSpinner();
        urunguncelleTF = new javax.swing.JButton();
        urunsilButton = new javax.swing.JButton();
        piechartpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        barchartpanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ürün Stok Durumu Paneli");
        setLocation(new java.awt.Point(1000, 25));

        urunTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ad", "Fiyat", "Stok"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        urunTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urunTableMouseClicked(evt);
            }
        });
        jScrollPane12.setViewportView(urunTable);
        if (urunTable.getColumnModel().getColumnCount() > 0) {
            urunTable.getColumnModel().getColumn(0).setResizable(false);
            urunTable.getColumnModel().getColumn(1).setResizable(false);
            urunTable.getColumnModel().getColumn(2).setResizable(false);
            urunTable.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        chartpanel.setPreferredSize(new java.awt.Dimension(266, 0));

        javax.swing.GroupLayout chartpanelLayout = new javax.swing.GroupLayout(chartpanel);
        chartpanel.setLayout(chartpanelLayout);
        chartpanelLayout.setHorizontalGroup(
            chartpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 515, Short.MAX_VALUE)
        );
        chartpanelLayout.setVerticalGroup(
            chartpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        jLabel12.setText("Ürün Adı:");

        jLabel13.setText("Ürün Fiyatı:");

        jLabel14.setText("Ürün Adeti");

        urunadetSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        urunekleButton.setText("Ürün Ekle");
        urunekleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunekleButtonActionPerformed(evt);
            }
        });

        jLabel15.setText("Ürün Adı:");

        jLabel16.setText("Ürün Fiyatı:");

        jLabel17.setText("Ürün Adeti");

        urunadetguncelleSpinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        urunguncelleTF.setText("Ürün Güncelle");
        urunguncelleTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunguncelleTFActionPerformed(evt);
            }
        });

        urunsilButton.setText("Ürün Sil");
        urunsilButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunsilButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(urunekleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(urunguncelleTF)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(129, 129, 129))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(7, 7, 7)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel17)
                                                .addComponent(jLabel16)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(urunadiTF, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                                        .addComponent(urunfiyatiTF)
                                        .addComponent(urunadiguncelleTF)
                                        .addComponent(urunfiyatiguncelleTF))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(urunadetSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(56, 56, 56))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(urunadetguncelleSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addContainerGap())
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(urunsilButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44)))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(urunadiTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(urunfiyatiTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(urunadetSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(urunekleButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urunadiguncelleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(urunfiyatiguncelleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(urunadetguncelleSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urunguncelleTF)
                    .addComponent(urunsilButton))
                .addGap(80, 80, 80))
        );

        piechartpanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        piechartpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                piechartpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                piechartpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                piechartpanelMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel1.setText("PieChart");

        javax.swing.GroupLayout piechartpanelLayout = new javax.swing.GroupLayout(piechartpanel);
        piechartpanel.setLayout(piechartpanelLayout);
        piechartpanelLayout.setHorizontalGroup(
            piechartpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(piechartpanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );
        piechartpanelLayout.setVerticalGroup(
            piechartpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, piechartpanelLayout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(38, 38, 38))
        );

        barchartpanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        barchartpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                barchartpanelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                barchartpanelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                barchartpanelMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Helvetica", 0, 18)); // NOI18N
        jLabel2.setText("BarChart");

        javax.swing.GroupLayout barchartpanelLayout = new javax.swing.GroupLayout(barchartpanel);
        barchartpanel.setLayout(barchartpanelLayout);
        barchartpanelLayout.setHorizontalGroup(
            barchartpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(barchartpanelLayout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jLabel2)
                .addContainerGap(90, Short.MAX_VALUE))
        );
        barchartpanelLayout.setVerticalGroup(
            barchartpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, barchartpanelLayout.createSequentialGroup()
                .addContainerGap(48, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(chartpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(piechartpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(barchartpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(piechartpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(barchartpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(chartpanel, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void urunekleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunekleButtonActionPerformed

        String productName = urunadiTF.getText();
        double fiyat =Double.parseDouble(urunfiyatiTF.getText());
        int stok = Integer.parseInt(urunadetSpinner.getValue().toString());
        
        processes.addProduct(productName, stok, fiyat);
        showProducts();


    }//GEN-LAST:event_urunekleButtonActionPerformed

    private void urunguncelleTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunguncelleTFActionPerformed
        int selectedindex = urunTable.getSelectedRow();
        int id = (int) urunTable.getValueAt(selectedindex, 0);
        String productName = urunadiguncelleTF.getText();
        double fiyat =Double.parseDouble(urunfiyatiguncelleTF.getText());
        int stok = Integer.parseInt(urunadetguncelleSpinner.getValue().toString());
        
        
        processes.updateProduct(id, productName, stok, fiyat);
            showProducts();
    }//GEN-LAST:event_urunguncelleTFActionPerformed

    private void urunTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urunTableMouseClicked

        int selectedindex = urunTable.getSelectedRow();
        
        urunadiguncelleTF.setText((String) urunTable.getValueAt(selectedindex, 1));
        urunfiyatiguncelleTF.setText(Double.toString((double) urunTable.getValueAt(selectedindex, 2))) ;
        urunadetguncelleSpinner.setValue(urunTable.getValueAt(selectedindex, 3));        
    }//GEN-LAST:event_urunTableMouseClicked

    private void urunsilButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunsilButtonActionPerformed
        
        int selectedindex = urunTable.getSelectedRow();
        int id = (int) urunTable.getValueAt(selectedindex, 0);

        processes.deleteProduct(id);
        showProducts();
        

    }//GEN-LAST:event_urunsilButtonActionPerformed

    private void piechartpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piechartpanelMouseClicked
        createPieChart();
        piechartpanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        barchartpanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));


        
    }//GEN-LAST:event_piechartpanelMouseClicked

    private void piechartpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piechartpanelMouseEntered
    }//GEN-LAST:event_piechartpanelMouseEntered

    private void piechartpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_piechartpanelMouseExited
    }//GEN-LAST:event_piechartpanelMouseExited

    private void barchartpanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barchartpanelMouseClicked
        createBarChart();
        piechartpanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        barchartpanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));
    }//GEN-LAST:event_barchartpanelMouseClicked

    private void barchartpanelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barchartpanelMouseEntered
    }//GEN-LAST:event_barchartpanelMouseEntered

    private void barchartpanelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_barchartpanelMouseExited
    }//GEN-LAST:event_barchartpanelMouseExited

    /**
     * @param args the command line arguments
     */
    
        public void showProducts(){      //model e tüm tarifleri gönderdiğimiz kısım
        model.setRowCount(0);
    
        ArrayList<Product> products = new ArrayList<Product>();
        products = processes.getProducts();
        
        if(products != null){
            for(Product product : products){
                Object[] next = {product.getId(),product.getAd(),product.getFiyat(),product.getAdet()};
                model.addRow(next);
            }
        }
    }
    
        private void createPieChart() {
        DefaultPieDataset dataset = new DefaultPieDataset();

        // Verileri getir ve grafiğe ekle
        for (Product product : processes.getProducts()) {
            dataset.setValue(product.getAd(), product.getAdet());
        }

        JFreeChart pieChart = ChartFactory.createPieChart3D(
                "Ürün Stok Durumu",  // Grafik başlığı
                dataset,            // Veri seti
                true,               // Legend gösterilsin mi
                true,
                false
        );

        // Grafik panelini oluştur ve GUI'ye ekle
        ChartPanel chartPanel = new ChartPanel(pieChart);
        chartPanel.setPreferredSize(new java.awt.Dimension(500, 500));
        chartpanel.setLayout(new BorderLayout());
        chartpanel.add(chartPanel, BorderLayout.CENTER);
        chartpanel.validate();
    }
        
        private void createBarChart() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

    // Verileri getir ve çubuk grafiğe ekle
    for (Product product : processes.getProducts()) {
        dataset.addValue(product.getAdet(), "Stok", product.getAd());
    }

    // Çubuk grafik oluştur
    JFreeChart barChart = ChartFactory.createBarChart3D(
            "Ürün Stok Durumu",   // Grafik başlığı
            "Ürünler",            // X ekseni başlığı
            "Stok Miktarı",       // Y ekseni başlığı
            dataset,              // Veri seti
            org.jfree.chart.plot.PlotOrientation.VERTICAL, // Çubukların yönü
            false,                // Legend gösterilsin mi
            true,
            false
    );

    // Grafik panelini oluştur ve GUI'ye ekle
    ChartPanel chartPanel = new ChartPanel(barChart);
    chartPanel.setPreferredSize(new java.awt.Dimension(500, 500)); // Panel boyutu
    chartpanel.setLayout(new BorderLayout());
    chartpanel.add(chartPanel, BorderLayout.CENTER);
    chartpanel.validate();
}
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StokPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StokPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StokPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StokPaneli.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StokPaneli().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel barchartpanel;
    private javax.swing.JPanel chartpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JPanel piechartpanel;
    private javax.swing.JTable urunTable;
    private javax.swing.JSpinner urunadetSpinner;
    private javax.swing.JSpinner urunadetguncelleSpinner;
    private javax.swing.JTextField urunadiTF;
    private javax.swing.JTextField urunadiguncelleTF;
    private javax.swing.JButton urunekleButton;
    private javax.swing.JTextField urunfiyatiTF;
    private javax.swing.JTextField urunfiyatiguncelleTF;
    private javax.swing.JButton urunguncelleTF;
    private javax.swing.JButton urunsilButton;
    // End of variables declaration//GEN-END:variables
}
